export const GO_TO_THE_STEP = 'GO_TO_THE_STEP';
//--------------------------------------------------------------
export const SELECT_SOURCE = 'SELECT_SOURCE';
export const CHANGE_IP = 'CHANGE_IP';
export const CHANGE_IP_STATUS = 'CHANGE_IP_STATUS';

export const CHANGE_STARTING_IP = 'CHANGE_STRATING_IP';
export const CHANGE_STARTING_IP_STATUS = 'CHANGE_STRATING_IP_STATUS';

export const CHANGE_ENDING_IP = 'CHANGE_ENDING_IP';
export const CHANGE_ENDING_IP_STATUS = 'CHANGE_ENDING_IP_STATUS';

export const SELECT_CSV_FILE = 'SELECT_CSV_FILE';
//-------------------------------------------------------------
export const SELECT_SNMP_OPTION = 'SELECT_SNMP_OPTION';
export const SELECT_LINK_OPTION = 'SELECT_LINK_OPTION';
export const SELECT_VLAN_OPTION = 'SELECT_VLAN_OPTION';
export const SELECT_PORTS_OPTION = 'SELECT_PORTS_OPTION';

export const SELECT_SNMP_VERSION = 'SELECT_SNMP_VERSION';
export const CHANGE_READ_COMMUNITY = 'CHANGE_READ_COMMUNITY';

export const SELECT_SECURITY_OPTION = 'SELECT_SECURITY_OPTION';
export const CHANGE_CONTEXT_NAME = 'CHANGE_CONTEXT_NAME';
export const CHANGE_CONTEXT_ENGINE_ID = 'CHANGE_CONTEXT_ENGINE_ID';
export const SELECT_AUTHENTICATION_CODE = 'SELECT_AUTHENTICATION_CODE';
export const CHANGE_AUTHENTICATION_PASSWORD = 'CHANGE_AUTHENTICATION_PASSWORD';

export const OPEN_DISCOVER_MODAL ='OPEN_DISCOVER_MODAL';
export const CLOSE_DISCOVER_MODAL ='CLOSE_DISCOVER_MODAL';
